### ISSUE TITLE
Custom prompt character font and background color

### ISSUE THREAD

**Issue by seonk** [iscooool/KeyMouse#1]
This app is great! I have tried similar applications and this one is the best so far! There is a small suggestion, if the font of the prompt character can be customized, wouldn't it be better? I have just tried to experience it. The only regret is about UI. One is font and the other is that there is no background color, like Vimium.
I'm very sorry, my application is not good, the above suggestion is the translation used.

**Comment by seonk** [comment]
Another suggestion is to customize the order of letters. At present, the first letter of two letters seems to be in the order of ABCD…… but AB…… is not necessarily the easiest key to press. If it is modified to be customizable, will it be better if everyone is most accustomed to pressing the key?

**Comment by iscooool** [comment]
Thanks for you suggestions! The configurability feature is on my plan. And I have noticed the letters ordering is not good enough. But it was too early to optimize the ordering at that time, I will consider it later. I'm sorry I'm too busy to implement these features in the next one or two months, but they're on my plan.
I'm glad you are enjoy this app.

**Comment by seonk** [comment]
This is really good news, and I look forward to the early realization of these functions! I have a group of friends who are keen to use only keyboard and not mouse. I will recommend this application to them. I believe they will like it as much as I do!
Thank you very much for providing such a great application!

**Comment by iscooool** [comment]
Configurable feature is available.

**Comment by seonk** [comment]
已下载，反馈两个问题，打字时JK键按下无效，我看了下配置文件里面有JK，还没有看具体是怎么回事。
另外就是 字符的边框看起来锯齿很严重，这个可以优化吗？

**Comment by iscooool** [comment]
J和K我是像vimium那样用来上滚和下滚的，如果你用不到可以暂时把它设置成你用不到的快捷键，现在我还没实现把某个键disable的功能。字符边框的锯齿我现在也没有考虑过这事，我这里用的2K的屏幕看起来不是很明显。
如果有问题可以另开issue，这个issue要关掉了。
