### ISSUE TITLE
Multiple displays support

### ISSUE THREAD

**Issue by dariusd** [iscooool/KeyMouse#11]
It would be nice if the app supports multiple displays. Nowadays it only works on a single screen - hints are displayed on the display selected as "Make this my main display" in Windows' Display Settings, leaving others screen blank of the KeyMouse hints.

**Comment by iscooool** [comment]
Currently I don't have multiple monitors for developing, sorry for leaving this issue open.

**Comment by dariusd** [comment]
> Currently I don't have multiple monitors for developing (...)

If you own at least two Windows 10 running machines you can make one of them act as an external display to the other one (described here: https://www.laptopmag.com/articles/turn-windows-10-pc-into-wirelss-display).

**Comment by iscooool** [comment]
support multiple monitors in new [release](https://github.com/iscooool/KeyMouse/releases/tag/V1.5).
