### ISSUE TITLE
Antivirus + IDP.Generic

### ISSUE THREAD

**Issue by ssinfod** [iscooool/KeyMouse#12]
I tried to run the 1.5.1 executable and I got the following message from my antivirus:
![image](https://user-images.githubusercontent.com/10925073/113058783-94999f00-917c-11eb-88a2-d5b558bf1c42.png)

Should I be worried ?
Do you know why KeyMouse is detected has having IDP.Generic virus ?

**Comment by iscooool** [comment]
I have registered a hook to detect keystroke of keyboard for updating cache. cache mechanism relies on it to decide when to update cache. Maybe it's thought as virus behavior. Is V1.5 also detected as virus?

**Comment by ssinfod** [comment]
Indeed version V1.5 does not seem to be detected by the anti-virus.

**Comment by ssinfod** [comment]
I also uploaded both versions on this website https://www.virustotal.com/
Both files were flagged as OK. (undetected)

So I suppose you can close this issue.
Greeting,
