### ISSUE TITLE
快速切换窗口 可替代 FastWindowSwitcher

### ISSUE THREAD

**Issue by seonk** [iscooool/KeyMouse#2]
好像您是中国人，我直接用中文提点建议，不借助谷歌翻译了……
发现您这款工具完全可以替代之前使用的一款效率神器：FastWindowSwitcher（https://github.com/JochenBaier/fastwindowswitcher）
如果您对此感兴趣的话，是否可以对此进一步优化：增加一个快速切换窗口的全局快捷键；提示的字符位于任务栏下对应标题 居中的位置。
目前是我是借助autohotkey，设置了一个快捷键，按下 切换焦点到任务栏，然后自动按下 Alt+;，也可以使用，只是样式有点丑而已。

**Comment by iscooool** [comment]
谢谢您的建议！但这个feature的优先级要比你之前提的issue低。很抱歉接下来的一个多月我都比较忙，可能没有时间更新。
这个应用到目前为止都很不完善，其中比较关键的问题是alt + ; 在一些元素比较多的窗口（比如浏览器）当中延迟比较高，而且延迟主要是UIAutomation的API带来的，而UIAtomation是我目前找到最适合完成需求的框架，这使得我难以进行性能上的优化。我想知道您作为使用者是怎么看这个问题的。
我还会继续优化这个应用。

**Comment by seonk** [comment]
还真没觉得延迟高，我觉得延迟完全在可接受范围内。说到浏览器，使用这款应用的人，应该是都在使用Vimium一类的插件吧，在浏览器里，插件 显然比这款应用的体验要更好一些，至少目前是这样。

跟延迟相比，我认为首先应该优化的 是崩溃的问题，经常按下快捷键 没有提示字符，然后看一下托盘图标 才发现不知道什么时候 软件已经消失了。

**Comment by iscooool** [comment]
我更新了下，不知有没有修复崩溃的问题，有的话再提issue吧。
