### ISSUE TITLE
How to disable some hotkeys?

### ISSUE THREAD

**Issue by quangdaist123** [iscooool/KeyMouse#20]
I want to disable some hotkeys instead of changing those hotkeys into something else.
I tried to set it to empty string but resulted "Unrecognized keybindings" error.
How I can do that? 
Thank you.

**Comment by iscooool** [comment]
Disabling hotkeys is not yet implemented.

**Comment by quangdaist123** [comment]
Can I use three-key combination hotkey?
The problem is that I can not use the hotkey that is currently assigned (ex: Alt+J) in another program.

**Comment by iscooool** [comment]
You can set something like `alt+win+shift+j`.

**Comment by quangdaist123** [comment]
Thank you for your fast replies. The app is great.
Wish you a nice day, bro!
