### ISSUE TITLE
Default to single left click

### ISSUE THREAD

**Issue by quangdaist123** [iscooool/KeyMouse#21]
Hello, 
I use single left click very very often. Is there an option to set the default click mode to single left click? That would be great!

**Comment by iscooool** [comment]
Add `selectModeSingle` in [V1.5.2](https://github.com/iscooool/KeyMouse/releases/tag/V1.5.2)

**Comment by quangdaist01** [comment]
Thanks a lot, I see that the README.md file has just been updated. I really appreciate your work but the code is very hard for me to follow ^^. Thank you for making such an interesting idea into a well-developed project
Good day to you!
