### ISSUE TITLE
鼠标单击、双击、右击

### ISSUE THREAD

**Issue by seonk** [iscooool/KeyMouse#3]
以操作资源管理器为例，用户可能不是想双击打开，而是鼠标右击，从右键菜单中选择某项操作，或者是只是想单击某个文件。目前好像是在资源管理器中 只有双击的动作。
我觉得思路是有两个，一个设置三个不同的启动快捷键，分别对应：双击、单击、右击，比方说 alt+; 双击，ctrl+alt+;单击，ctrl+alt+shift+;右击，快捷键由用户自定义设置。
第二个思路是 快捷键只有一个，出来提示的字母后，默认 直接按字母 就是双击操作，按下shift后再按字母 就是单击，按下ctrl后再按字母就是右击。

另外问一下，关于前面提过的自定义配置的功能，你大约什么时候可以有时间增加这些功能呢？我近期在准备录制几期关于Windows下高效神器的视频，我想把这款工具也讲一下。

**Comment by iscooool** [comment]
谢谢你的建议！对于单、双击和右击这一特性，因为我个人倾向于少占用全局快捷键的，所以如果要实现的话我倾向于写成自定义快捷键的形式，用户选择是否用这些功能，当然第二个思路也可以。
目前我还是学生，所以临近期末会比较忙，可能差不多一月中旬才会有时间。
目前程序还很不完善，对我自己来说也没达到比较可用的程度，所以看到你说要讲一下这款工具我还觉得程序还没到那种程度，当然讲不讲是您的自由。
