### ISSUE TITLE
按键无效

### ISSUE THREAD

**Issue by seonk** [iscooool/KeyMouse#4]
![KeyMouse](https://user-images.githubusercontent.com/55017663/71776796-06af2280-2fd2-11ea-839a-2d73bdc7dcbb.gif)
没有屏蔽输入法，导致按键无效，如果每次要切换一下输入法就太麻烦了。

**Comment by iscooool** [comment]
请问你用的是什么输入法？我用win10自带的没有这个问题，所以没有考虑过这种情况。

**Comment by seonk** [comment]
我用的是搜狗输入法，之前版本也是用这个输入法，是没有这个问题的。

**Comment by iscooool** [comment]
我刚下了搜狗输入法试了一下，还是没有复现问题。

**Comment by seonk** [comment]
好像还不是我说的输入法的问题，我刚试了下切换输入法，切换到英文、微软便宜，都是按键无效的，只是没有出来像搜狗这样的选择框。
配置文件我只修改了字体，jk改成了win+j，win+k，跟这里会有关系吗？

**Comment by seonk** [comment]
果然是这样的。

**Comment by seonk** [comment]
修改jk为 win+j，win+k 导致的。

**Comment by iscooool** [comment]
这个是因为win+j和win+k快捷键已经被系统占用了，导致后续的快捷键无法注册，我之后再修复这个问题。
