### ISSUE TITLE
config.json not being read

### ISSUE THREAD

**Issue by spind0g** [iscooool/KeyMouse#6]
changing the settings in the `config.json` file doesn't work and the program takes control over the **J** and **K** keys on programs that have scrollbars.

**Comment by iscooool** [comment]
Can you post your config.json? If there are syntax errors or key conflicts in config.json, program will use default configuration instead which will occupy J and K keys.

**Comment by spind0g** [comment]
Thanks for pointing that out. I actually commented out both the settings for `scrollUp` and `scrollDown`.
