### ISSUE TITLE
Right click instead of left click

### ISSUE THREAD

**Issue by fdawans** [iscooool/KeyMouse#9]
Hello,

First of all, thank you for this amazing program, I have been looking for this for some time and I just tried it today.
However, I would like to know if you could add an option to swap the mouse buttons as I am using the right button to click on Windows. 

Thank you,

**Comment by iscooool** [comment]
If I don't misunderstand you, do you mean right click the area where the hint is on? For example, alt+; ---> shift+a ---> c  will right click the hint C.

**Comment by fdawans** [comment]
Sorry if it is not clear. 
I mean that I am using my mouse in my left hand so that the default click is right click.
That means that in my Keymouse, the clicks are inverted compared to your setup so:
alt+; ---> shift+a ---> c = left click
alt+; ---> c = right click

**Comment by iscooool** [comment]
I have updated a new release for solving this issue.
